// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace test2.Models
{
    public partial class AdditionalPeople
    {
        [JsonIgnore]
        public int AdditionalId { get; set; }
        public int Sdid { get; set; }
        public string AdditionalFirstName { get; set; } = null!;
        public string AdditionalLastName { get; set; } = null!;
        public string AdditionalEmail { get; set; } = null!;
        public long AdditionalPhone { get; set; }
        public string UserCreated { get; set; } = null!;
        public DateTime? UserCreatedDate { get; set; }
        public string? UserUpdated { get; set; }
        public DateTime? UserUpdatedDateTime { get; set; }

        [JsonIgnore]
        public virtual SurveyInfo? Sd { get; set;  } = null!;
    }
}