// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace test2.Models
{
    public partial class Questions
    {
        public Questions()
        {
            QAndA = new HashSet<QAndA>();
        }

        public int QuestionId { get; }
        public string QuestionDesc { get; set; } = null!;
        public string UserCreated { get; set; } = null!;
        public DateTime? UserCreatedDateTime { get; set; }
        public string? UserUpdated { get; set; }
        public DateTime? UserUpdatedDateTime { get; set; }

        [JsonIgnore]
        public virtual ICollection<QAndA>? QAndA { get; }
    }
}