// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.Text.Json.Serialization;
namespace test2.Models
{
    public partial class SurveyInfo
    {
        public SurveyInfo()
        {
            AdditionalPeople = new HashSet<AdditionalPeople>();
            Gaurdians = new HashSet<Gaurdians>();
            Interviewers = new HashSet<Interviewers>();
            QAndA = new HashSet<QAndA>();
        }

        [JsonIgnore]
        public int Sdid { get; set; }
        public string JuvenileFirstName { get; set; } = null!;
        public string JuvenileLastName { get; set; } = null!;
        public int SurveyId { get; set; }
        public string SurveyAnswer { get; set; } = null!;
        public string? UserCreated { get; set; }
        public DateTime? UserCreatedDateTime { get; set; }
        public string? UserUpdated { get; set; }
        public DateTime? UserUpdatedDateTime { get; set; }

        public virtual ICollection<AdditionalPeople>? AdditionalPeople { get; set; }
        public virtual ICollection<Gaurdians>? Gaurdians { get; set; }
        public virtual ICollection<Interviewers>? Interviewers { get; set; }
        public virtual ICollection<QAndA>? QAndA { get; set; }
    }
}